version: "3"

services:
  go-discord-bot:
    image: mgerb/go-discord-bot:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./clips:/server/clips
      - ./sounds:/server/sounds
      - ./youtube:/server/youtube
      - ./config.json:/server/config.json:ro
      - ./data.db:/server/data.db
      - ./logrus.log:/server/logrus.log  

      - /usr/local/bin/yt-dlp:/usr/bin/yt-dlp
